version: "3"

services:
  todosDB:
    image: postgres:15.3
    container_name: todos-todosDB
    restart: always
    ports:
      - "5440:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todos
    volumes:
      - ./postgres:/var/lib/postgresql/data
